/* ======================================================================
	FileName: npReader.c
   Purpose:  To understand how to use a named pipe to establish
				 communication between two pprocesses.

	Problem: Suppose one Writer tells her story to a reader 
				little-by-little based on reader's opinion. Writer tells
				her story as long as reader wants to listen. A named
				pipe is used for communication. That means both Writer and
				reader use the same named pipe for sending their message
				to others.

	Tasks of Reader:
		1. Check whether any name is provided from the terminal for
			a named pipe.
		2. Read Writer's story part-by-part from the pipe by sending 
			'y' message into the pipe.
		3. Quit by pressing 'n'.				
	----------------------------------------------------------------------
	How to Run: 
	A. At a terminal, compile and run 'npReader.c'
		$ gcc npReader.c -o npReader
		$ ./npReader <pipeName>
		[ i.e. $./npReader RoyalFamily]

	B. Before or after running 'npReader' process, compile and run 
		'npWriter.c' at another terminal.
		$ gcc npWriter.c -o npWriter
		$ ./npWriter <pipeName>
		[ i.e. $./npWriter RoyalFamily]
	----------------------------------------------------------------------
	Note:
	A. Running multiple 'npReader' processes can cause problems,
		since one npReader's opinion can be sent to other npReader 
		process instead of npWriter process.
	----------------------------------------------------------------------
   Sangeeta Biswas, Ph.D.
	Assistant Professor,
	Dept. of CSE, University of Rajshahi,
	Rajshahi-6205, Bangladesh.
	sangeeta.cse.ru@gmail.com / sangeeta.cse@ru.ac.bd
	----------------------------------------------------------------------
	19/11/2017
	======================================================================
*/

#include <stdlib.h>	// For exit()
#include <fcntl.h>	// For open()
#include <unistd.h>	// For close()
#include <stdio.h>	//	For perror()
#include <string.h>	// For strlen()


#define BUFF_SZ 1024
#define OPINION_SZ 3

int main(int argc, char *argv[]){
	int fd, rdSz;
	char storyBuffer[BUFF_SZ];
	char opinion[OPINION_SZ];
	char *msg = "Usage: ./npReader <pipeName>\n";
	
	/* =====================================================
		Check whether the name of the pipe is provided. 
		===================================================== 
	*/
	if(argc != 2){
		write(1, msg, strlen(msg) + 1);
		exit(EXIT_FAILURE);
	}

	while(1){
		/* =====================================================
			 Read a part of the story from the named pipe. 
			===================================================== */
		fd = open(argv[1], O_RDONLY);
		if(fd == -1){
			perror("Error during open()");
			exit(EXIT_FAILURE);
		}
   	read(fd, storyBuffer, BUFF_SZ);
		close(fd);
		write(1, storyBuffer, strlen(storyBuffer) + 1);

		/* =====================================================
			  Write opinion (y/n) into the named pipe. 
			===================================================== 
		*/
		rdSz = read(0, opinion, OPINION_SZ);
		/* For the new line character generated by the ENTER
			key, opinion's size will be 1 larger than its
			original size. This new line character needs to be 
			discarded. Therefore, the null character is added
			at the (rdSz-1)-th position. '\0' will make opinion
			a valid string.
		*/
		opinion[rdSz-1] = '\0';
		fd = open(argv[1], O_WRONLY);
		write(fd, opinion, strlen(opinion) + 1);
		close(fd);
		if(strcmp(opinion,"n") == 0)		
			break;
	}

	exit(EXIT_SUCCESS);
}
